refactor: refactor to use AWS SDK v3 signing package
ScaleLeap/aws4-axios pull request #1
Opened 2021-03-26 09:59 UTC by nguyentoanit

2021-03-29 09:10 UTC, nguyentoanit commented on src/interceptor.ts
> +    const result = await signer.sign(minimalRequest);
@moltar : This PR is still WIP. I'm updating tests.
But you could take a look my approach to use AWS SDK v3 signing package.
How do you think about them?

2021-03-29 12:03 UTC, moltar commented on src/interceptor.ts
> +    const result = await signer.sign(minimalRequest);
I think it looks fine.

One thing to remember is that we don't want to have any breaking changes in the final design. I am not saying there are now, but just emphasizing this, in case I forgot to mention it before :)

2021-03-30 08:08 UTC, moltar requested changes

2021-03-30 08:08 UTC, moltar commented on package.json
> +    "@aws-sdk/signature-v4": "^3.6.1"
Let's match versions with `@aws-sdk/client-sts`, as this is a monorepo.

2021-03-30 08:10 UTC, moltar commented
@andrestone please take a look at this as well

2021-03-30 11:47 UTC, andrestone requested changes

2021-03-30 11:47 UTC, andrestone commented on src/interceptor.ts
> -  signQuery?: boolean;
We should still expose this option in order not to have any breaking changes. This pattern is implemented as `SignatureV4.presign()`.

2021-03-31 09:51 UTC, nguyentoanit commented on src/interceptor.ts
> +      config.params = query;
@andrestone : I exposed and supported `signQuery` option here. Please help me review again. Thanks.

2021-04-24 07:11 UTC, moltar commented
@andrestone please review

2021-04-26 08:36 UTC, andrestone approved these changes

2021-04-26 08:54 UTC, merged